# data from https://opentdb.com/api_config.php
question_data = [
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The Great Wall of China is visible from the moon.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Soulja Boy&#039;s &#039;Crank That&#039; won a Grammy for Best Rap Song in 2007.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "Skateboarding will be included in the 2020 Summer Olympics in Tokyo.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Rabbits are rodents.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An Astronomical Unit is the distance between Earth and the Moon.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean",
     "difficulty": "medium",
     "question": "In &quot;Star Trek: The Next Generation&quot;, Data is the only android in existence.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "hard",
     "question": "The character Plum from &quot;No Game No Life&quot; is a girl.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
